version: "3.9"
services:
  hiking-match:
    build:
      context: ./hiking-match-service/
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${HM_DB_URL:-jdbc:postgresql://hiking-match-db:5432/hiking-match}
      DB_USER: ${HM_DB_USER:-postgres}
      DB_PASSWORD: ${HM_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
    depends_on:
      - hiking-match-db
    networks:
      - hiking_match_network

  hiking-match-db:
    image: postgres
    container_name: hiking-match-db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hiking-match}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - hiking_match_data:/var/lib/postgresql/data
    networks:
      - hiking_match_network

volumes:
  hiking_match_data:

networks:
  hiking_match_network:
