spring.application.name=hiking-routes-service
server.port=8080

#spring.data.mongodb.uri=mongodb://localhost:27017/hiking-routes
spring.data.mongodb.uri=${DB_URL}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.new.topic.name=${RABBITMQ_NEW_TOPIC_NAME}
rabbitmq.new.queue.name=${RABBITMQ_NEW_QUEUE_NAME}
rabbitmq.new.routing.key=${RABBITMQ_NEW_ROUTING_KEY}
#spring.rabbitmq.host=rabbitmq
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=kevinmq
#spring.rabbitmq.password=kevinmq
#rabbitmq.new.topic.name=routeTopic
#rabbitmq.new.queue.name=routeQueue
#rabbitmq.new.routing.key=routeNew
