spring.application.name=hiking-match-service
server.port=8081

#.datasource.url=jdbc:postgresql://localhost:5440/hiking-match
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans= false
#spring.jpa.hibernate.ddl-auto=create

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.new.queue.name=${RABBITMQ_NEW_QUEUE_NAME}

sendgrid.api.key=${SENGRID_API_KEY}
sendgrid.from.email=${SENGRID_FROM_EMAIL}

#jwt.secret=c2VjcmV0a2V5dGFza2luZ3NlY3JldGtleXRhc2tpbmdzZWNyZXRrZXl0YXNraW5nc2VjcmV0a2V5dGFza2luZw==
#jwt.expiration=3600000

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

clients.urls.routes=${CLIENTS_URLS_ROUTES}
